// required for old g++ to compile PRId64 macros, see
// https://github.com/pytorch/pytorch/issues/3571
// for context
#ifndef __STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
#endif

// an external backend might generate file within its code tree
// and check all the source files within the tree with clang-format.
// so, disable it since the backend might have a different config.
// clang-format off

// NOTE: This condition is true for all PyTorch internal libraries, it
//       just excludes external projects such as torch_xla which
//       re-use some of the PyTorch codegen machinery.
#if defined(CAFFE2_BUILD_MAIN_LIB)        || \
    defined(TORCH_CUDA_BUILD_MAIN_LIB)    || \
    defined(TORCH_HIP_BUILD_MAIN_LIB)     || \
    defined(TORCH_XPU_BUILD_MAIN_LIB)     || \
    defined(TORCH_CUDA_CU_BUILD_MAIN_LIB) || \
    defined(TORCH_CUDA_CPP_BUILD_MAIN_LIB)
#define TORCH_ASSERT_ONLY_METHOD_OPERATORS
#endif

// @generated by gen_backend_stubs.py from RegisterDispatchKey.cpp

#include <c10/core/TensorImpl.h>
#include <c10/core/Allocator.h>
#include <ATen/DeviceGuard.h>
#include <ATen/NamedTensorUtils.h>
#include <ATen/Utils.h>
#include <ATen/WrapDimUtils.h>
#include <ATen/Dispatch.h>
#include <c10/util/ExclusivelyOwned.h>
#include <c10/util/Half.h>
#include <c10/core/UndefinedTensorImpl.h>
#include <optional>
#include <ATen/Tensor.h>
#include <ATen/native/Resize.h>

#include <cstddef>
#include <functional>
#include <memory>
#include <utility>

#include <ATen/Config.h>
#include <ATen/core/op_registration/adaption.h>
#include <torch/library.h>

#include "torch_dpu/csrc/aten/PrivateUse1NativeFunctions.h"
#include <ATen/NativeFunctions.h>
#include <ATen/Functions.h>
#include <c10/macros/Macros.h>
#include <ATen/Functions.h>

namespace at {
namespace {
C10_DIAGNOSTIC_PUSH_AND_IGNORED_IF_DEFINED("-Wunused-function")

void resize_out(const Tensor &out, IntArrayRef sizes, IntArrayRef strides, const TensorOptions &options) {
  TORCH_CHECK(options.dtype() == out.dtype(),
      "Expected out tensor to have dtype ", options.dtype(), ", but got ", out.dtype(), " instead");
  TORCH_CHECK(options.device() == out.device(),
      "Expected out tensor to have device ", options.device(), ", but got ", out.device(), " instead");
  const bool resized = at::native::resize_output(out, sizes);
  // Only restride if a resize occurred; otherwise we ignore the (advisory)
  // strides from the meta function and directly use the output tensor's
  // preexisting strides
  if (resized) {
    if (!strides.empty()) {
      TORCH_INTERNAL_ASSERT(!options.memory_format_opt().has_value());
      // TODO: avoid the redispatch here
      out.as_strided_(sizes, strides);
    } else if (options.memory_format_opt().has_value()) {
      out.unsafeGetTensorImpl()->empty_tensor_restride(*options.memory_format_opt());
    }
  }
}

void check_inplace(const Tensor &self, IntArrayRef sizes, const TensorOptions &options) {
  // These checks are needed on those operators that:
  //   1) don't use 'TensorIterator' (e.g. 'addmm' and 'baddbmm')
  //   2) have particular typing rules (e.g. 'cumsum' and 'cumprod')
  // For other operators (e.g. 'add'), 'TensorIterator' already checks
  // these things separately.
  TORCH_CHECK(options.dtype() == self.dtype(),
      "Bad in-place call: ",
      "input tensor dtype ", self.dtype(), " and output tensor dtype ", options.dtype(), " should match");
  TORCH_CHECK(options.device() == self.device(),
      "Bad in-place call: ",
      "input tensor device ", self.device(), " and output tensor device ", options.device(), " should match");
  TORCH_CHECK(sizes == self.sizes(),
      "Bad in-place call: ",
      "input tensor size ", self.sizes(), " and output tensor size ", sizes, " should match");
}
C10_DIAGNOSTIC_POP()
} // namespace
} // namespace at

// See template file RegisterDispatchDefinitions.ini
namespace at {
// NB: TORCH_LIBRARY_IMPL must be in an anonymous namespace to avoid
// ambiguity with conflicting identifiers that may have been defined in
// at namespace already.
namespace {
namespace {
at::Tensor & wrapper_PrivateUse1_out_add_out(const at::Tensor & self, const at::Tensor & other, const at::Scalar & alpha, at::Tensor & out) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::add_out(self, other, alpha, out);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1__as_strided(const at::Tensor & self, c10::SymIntArrayRef size, c10::SymIntArrayRef stride, ::std::optional<c10::SymInt> storage_offset) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::as_strided(self, C10_AS_INTARRAYREF_SLOW(size), C10_AS_INTARRAYREF_SLOW(stride), storage_offset.has_value() ? ::std::make_optional(storage_offset->guard_int(__FILE__, __LINE__)) : ::std::nullopt);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1__cat(const at::ITensorListRef & tensors, int64_t dim) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::cat(tensors, dim);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1___copy_from(const at::Tensor & self, const at::Tensor & dst, bool non_blocking) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::_copy_from(self, dst, non_blocking);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1_memory_format_empty(c10::SymIntArrayRef size, ::std::optional<at::ScalarType> dtype, ::std::optional<at::Layout> layout, ::std::optional<at::Device> device, ::std::optional<bool> pin_memory, ::std::optional<at::MemoryFormat> memory_format) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::empty(C10_AS_INTARRAYREF_SLOW(size), dtype, layout, device, pin_memory, memory_format);
}
} // anonymous namespace
namespace {
const at::Tensor & wrapper_PrivateUse1__resize_(const at::Tensor & self, c10::SymIntArrayRef size, ::std::optional<at::MemoryFormat> memory_format) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::resize_(self, C10_AS_INTARRAYREF_SLOW(size), memory_format);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1__empty_strided(c10::SymIntArrayRef size, c10::SymIntArrayRef stride, ::std::optional<at::ScalarType> dtype, ::std::optional<at::Layout> layout, ::std::optional<at::Device> device, ::std::optional<bool> pin_memory) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::empty_strided(C10_AS_INTARRAYREF_SLOW(size), C10_AS_INTARRAYREF_SLOW(stride), dtype, layout, device, pin_memory);
}
} // anonymous namespace
namespace {
at::Tensor & wrapper_PrivateUse1_Scalar_fill_(at::Tensor & self, const at::Scalar & value) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::fill_(self, value);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1___to_copy(const at::Tensor & self, ::std::optional<at::ScalarType> dtype, ::std::optional<at::Layout> layout, ::std::optional<at::Device> device, ::std::optional<bool> pin_memory, bool non_blocking, ::std::optional<at::MemoryFormat> memory_format) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::_to_copy(self, dtype, layout, device, pin_memory, non_blocking, memory_format);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1_device_to(const at::Tensor & self, at::Device device, at::ScalarType dtype, bool non_blocking, bool copy, ::std::optional<at::MemoryFormat> memory_format) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::to(self, device, dtype, non_blocking, copy, memory_format);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1_dtype_to(const at::Tensor & self, at::ScalarType dtype, bool non_blocking, bool copy, ::std::optional<at::MemoryFormat> memory_format) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::to(self, dtype, non_blocking, copy, memory_format);
}
} // anonymous namespace
namespace {
at::Scalar wrapper_PrivateUse1___local_scalar_dense(const at::Tensor & self) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::_local_scalar_dense(self);
}
} // anonymous namespace
namespace {
at::Tensor & wrapper_PrivateUse1_source_Storage_set_(at::Tensor & self, at::Storage source) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::set_(self, source);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1__view(const at::Tensor & self, c10::SymIntArrayRef size) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::view(self, C10_AS_INTARRAYREF_SLOW(size));
}
} // anonymous namespace
namespace {
at::Tensor & wrapper_PrivateUse1_Tensor_out_bitwise_and_out(const at::Tensor & self, const at::Tensor & other, at::Tensor & out) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::bitwise_and_out(self, other, out);
}
} // anonymous namespace
namespace {
at::Tensor & wrapper_PrivateUse1_Scalar_out_ne_out(const at::Tensor & self, const at::Scalar & other, at::Tensor & out) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::ne_out(self, other, out);
}
} // anonymous namespace
namespace {
at::Tensor & wrapper_PrivateUse1_Tensor_out_eq_out(const at::Tensor & self, const at::Tensor & other, at::Tensor & out) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::eq_out(self, other, out);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1__isfinite(const at::Tensor & self) {
    // No device check
  // DeviceGuard omitted
  return at_dpu::native::DPUNativeFunctions::isfinite(self);
}
} // anonymous namespace
TORCH_LIBRARY_IMPL(aten, PrivateUse1, m) {
    m.impl("add.out",
    TORCH_FN(wrapper_PrivateUse1_out_add_out));
    m.impl("as_strided",
    TORCH_FN(wrapper_PrivateUse1__as_strided));
    m.impl("cat",
    TORCH_FN(wrapper_PrivateUse1__cat));
    m.impl("_copy_from",
    TORCH_FN(wrapper_PrivateUse1___copy_from));
    m.impl("empty.memory_format",
    TORCH_FN(wrapper_PrivateUse1_memory_format_empty));
    m.impl("resize_",
    TORCH_FN(wrapper_PrivateUse1__resize_));
    m.impl("empty_strided",
    TORCH_FN(wrapper_PrivateUse1__empty_strided));
    m.impl("fill_.Scalar",
    TORCH_FN(wrapper_PrivateUse1_Scalar_fill_));
    m.impl("_to_copy",
    TORCH_FN(wrapper_PrivateUse1___to_copy));
    m.impl("to.device",
    TORCH_FN(wrapper_PrivateUse1_device_to));
    m.impl("to.dtype",
    TORCH_FN(wrapper_PrivateUse1_dtype_to));
    m.impl("_local_scalar_dense",
    TORCH_FN(wrapper_PrivateUse1___local_scalar_dense));
    m.impl("set_.source_Storage",
    TORCH_FN(wrapper_PrivateUse1_source_Storage_set_));
    m.impl("view",
    TORCH_FN(wrapper_PrivateUse1__view));
    m.impl("bitwise_and.Tensor_out",
    TORCH_FN(wrapper_PrivateUse1_Tensor_out_bitwise_and_out));
    m.impl("ne.Scalar_out",
    TORCH_FN(wrapper_PrivateUse1_Scalar_out_ne_out));
    m.impl("eq.Tensor_out",
    TORCH_FN(wrapper_PrivateUse1_Tensor_out_eq_out));
    m.impl("isfinite",
    TORCH_FN(wrapper_PrivateUse1__isfinite));
};
} // anonymous namespace
namespace privateuse1 {
} // namespace privateuse1
} // namespace at
